<a href="https://colab.research.google.com/github/Matheusbcy/-Data-Science-IA-/blob/main/IA%20com%20RAPIDS/IA_com_RAPIDS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CuDF - RAPIDS

In [2]:
!git clone https://github.com/rapidsai/rapidsai-csp-utils.git

Cloning into 'rapidsai-csp-utils'...
remote: Enumerating objects: 616, done.
remote: Counting objects: 100% (182/182), done.
remote: Compressing objects: 100% (97/97), done.
remote: Total 616 (delta 140), reused 88 (delta 85), pack-reused 434 (from 3)
Receiving objects: 100% (616/616), 203.58 KiB | 16.96 MiB/s, done.
Resolving deltas: 100% (314/314), done.

In [4]:
!python rapidsai-csp-utils/colab/pip-install.py

Installing RAPIDS remaining 25.10 libraries
Using Python 3.12.12 environment at: /usr
Resolved 176 packages in 10.69s
Prepared 18 packages in 23.84s
Uninstalled 11 packages in 210ms
Installed 18 packages in 87ms
 - bokeh==3.7.3
 + bokeh==3.6.3
 + cucim-cu12==25.10.0
 + cugraph-cu12==25.10.1
 + cuxfilter-cu12==25.10.0
 + datashader==0.18.2
 - holoviews==1.22.0
 + holoviews==1.20.2
 + jupyter-server-proxy==4.4.0
 - nvidia-cublas-cu12==12.6.4.1
 + nvidia-cublas-cu12==12.9.1.4
 - nvidia-cuda-nvcc-cu12==12.5.82
 + nvidia-cuda-nvcc-cu12==12.9.86
 - nvidia-cuda-nvrtc-cu12==12.6.77
 + nvidia-cuda-nvrtc-cu12==12.9.86
 - nvidia-cufft-cu12==11.3.0.4
 + nvidia-cufft-cu12==11.4.1.4
 - nvidia-curand-cu12==10.3.7.77
 + nvidia-curand-cu12==10.3.10.19
 - nvidia-cusolver-cu12==11.7.1.2
 + nvidia-cusolver-cu12==11.7.5.82
 - nvidia-cusparse-cu12==12.5.4.2
 + nvidia-cusparse-cu12==12.5.10.65
 - panel==1.8.3
 + panel==1.7.5
 + pyct==0.6.0
 - shapely==2.1.2
 + shapely==2.0.7
 + simpervisor==1.0.0

        ***********************************************************************
        The pip install of RAPIDS is complete.

        Please do not run any further installation from the conda based installation methods, as they may cause issues!

        Please ensure that you're pulling from the git repo to remain updated with the latest working install scripts.

        Troubleshooting:
            - If there is an installation failure, please check back on RAPIDSAI owned templates/notebooks to see how to update your personal files.
            - If an installation failure persists when using the latest script, please make an issue on https://github.com/rapidsai-community/rapidsai-csp-utils
        ***********************************************************************

# Com o Pandas (CPU)

In [5]:
import pandas as pd

print(pd.__version__)

2.2.2

In [9]:
df = pd.DataFrame()
df["id"] = [0, 1, 2, 2, 3, 3, 3]
df["val"] = [float(i + 10) for i in range(7)]
print(df)

   id   val
0   0  10.0
1   1  11.0
2   2  12.0
3   2  13.0
4   3  14.0
5   3  15.0
6   3  16.0

In [8]:
soma = df["val"].sum()
print(soma)

91.0

# Com o cuDF (GPU)

In [10]:
import cudf
print(cudf.__version__)

25.10.00

In [11]:
df = cudf.DataFrame()
df["id"] = [0, 1, 2, 2, 3, 3, 3]
df["val"] = [float(i + 10) for i in range(7)]
print(df)

   id   val
0   0  10.0
1   1  11.0
2   2  12.0
3   2  13.0
4   3  14.0
5   3  15.0
6   3  16.0

In [14]:
soma = df["val"].sum()
print(soma)

91.0

# Familiarizando com o cuDF

## Criação do objeto

In [15]:
s = cudf.Series([1, 2, None, 3, 4])
print(s)

0       1
1       2
2    <NA>
3       3
4       4
dtype: int64

In [18]:
df = cudf.DataFrame({
    "a": list(range(10)),
    "b": list(reversed(range(10))),
    "c": list(range(10))
})

df

   a  b  c
0  0  9  0
1  1  8  1
2  2  7  2
3  3  6  3
4  4  5  4
5  5  4  5
6  6  3  6
7  7  2  7
8  8  1  8
9  9  0  9

In [20]:
df_p = pd.DataFrame({"a": [0, 1, 2, 3], "b": [0.1, 0.2, None, 0.3]})

In [23]:
# Converter um dataframe pandas em um dataframe cudf
df_c = cudf.DataFrame.from_pandas(df_p)

## Visualização dos dados

In [24]:
df.head(2)

   a  b  c
0  0  9  0
1  1  8  1

In [26]:
df.sort_values(by = 'b')

   a  b  c
9  9  0  9
8  8  1  8
7  7  2  7
6  6  3  6
5  5  4  5
4  4  5  4
3  3  6  3
2  2  7  2
1  1  8  1
0  0  9  0

# Seleção

In [28]:
print(df.loc[3:5])

   a  b  c
3  3  6  3
4  4  5  4
5  5  4  5

In [29]:
print(df.loc[3:5, ['a', 'b']])

   a  b
3  3  6
4  4  5
5  5  4

In [30]:
print(df.iloc[0])

a    0
b    9
c    0
Name: 0, dtype: int64

In [31]:
df.iloc[0:3, 0:2]

   a  b
0  0  9
1  1  8
2  2  7

# Condicionamentos e indexação booleana

In [32]:
print(df)

   a  b  c
0  0  9  0
1  1  8  1
2  2  7  2
3  3  6  3
4  4  5  4
5  5  4  5
6  6  3  6
7  7  2  7
8  8  1  8
9  9  0  9

In [34]:
print(df[df.b > 5])

   a  b  c
0  0  9  0
1  1  8  1
2  2  7  2
3  3  6  3

# Dados Faltantes

In [37]:
print(s.fillna(999))

0      1
1      2
2    999
3      3
4      4
dtype: int64

In [38]:
print(s.dropna())

0    1
1    2
3    3
4    4
dtype: int64

# Estatisticas

In [39]:
import numpy as np

In [42]:
s = cudf.Series(np.arange(10).astype(np.float32))

In [44]:
s

0    0.0
1    1.0
2    2.0
3    3.0
4    4.0
5    5.0
6    6.0
7    7.0
8    8.0
9    9.0
dtype: float32

In [45]:
print(s.mean())
print(s.var())
print(s.std())

4.5
9.166667
3.0276504

In [46]:
print(df.describe())

              a         b         c
count  10.00000  10.00000  10.00000
mean    4.50000   4.50000   4.50000
std     3.02765   3.02765   3.02765
min     0.00000   0.00000   0.00000
25%     2.25000   2.25000   2.25000
50%     4.50000   4.50000   4.50000
75%     6.75000   6.75000   6.75000
max     9.00000   9.00000   9.00000