<a href="https://colab.research.google.com/github/Matheusbcy/-Data-Science-IA-/blob/main/PyTorch/Classifica%C3%A7ao%20Binaria/Forma%C3%A7%C3%A3o_Deep_Learning_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Projeto 1: Classificação binária brest cancer

## Etapa 1: Importação das bibliotecas

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, accuracy_score

In [ ]:
import torch
torch.__version__

'2.9.0+cu126'

In [ ]:
import torch.nn as nn

## Etapa 2: Base de dados

In [ ]:
np.random.seed(123)
torch.manual_seed(123)

In [ ]:
previsores = pd.read_csv("/content/entradas_breast.csv")
classe = pd.read_csv("/content/saidas_breast.csv")

In [ ]:
previsores.shape

(569, 30)

In [ ]:
previsores.head()

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave_points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave_points_worst,symmetry_worst,fractal_dimension_worst
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,186.0000,275.0000,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,243.0000,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,173.00000
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,198.0000,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.1374,205.0000,0.4000,0.1625,0.2364,0.07678

In [ ]:
classe.head()

   0
0  0
1  0
2  0
3  0
4  0

In [ ]:
np.unique(classe)

array([0, 1])

In [ ]:
previsores_train, previsores_test, classe_train, classe_test = train_test_split(previsores, classe, test_size=0.25)

In [ ]:
previsores_train.shape, classe_train.shape

((426, 30), (426, 1))

In [ ]:
previsores_test.shape, classe_test.shape

((143, 30), (143, 1))

## Etapa 3: Transformação dos dados para tensores

In [ ]:
type(np.array(previsores_train))

numpy.ndarray

In [ ]:
previsores_train = torch.tensor(np.array(previsores_train), dtype = torch.float)
classe_train = torch.tensor(np.array(classe_train), dtype = torch.float)

In [ ]:
type(previsores_train), type(classe_train)

(torch.Tensor, torch.Tensor)

In [ ]:
dataset = torch.utils.data.TensorDataset(previsores_train, classe_train)

In [ ]:
type(dataset)

In [ ]:
train_loader = torch.utils.data.DataLoader(dataset, batch_size = 10, shuffle = True)