<a href="https://colab.research.google.com/github/Matheusbcy/-Data-Science-IA-/blob/main/Deep%20Learning/Redes%20Neurais%20Artificiais/Classifica%C3%A7%C3%A3o_Binaria_base_brest_cancer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Classificação binária - Brest Cancer simples

In [1]:
import pandas as pd

In [2]:
# Atributos Previsores

X = pd.read_csv("/content/entradas_breast.csv")
X

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave_points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave_points_worst,symmetry_worst,fractal_dimension_worst
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.12380,0.18660,0.2416,186.0000,275.0000,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.14440,0.42450,0.4504,243.0000,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,173.00000
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,198.00000,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.13740,205.00000,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,111.00000,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.45,26.40,166.10,2027.0,141.00000,0.21130,0.4107,0.2216,206.0000,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,144.00000,0.09791,0.1752,0.05533,...,23.69,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,159.0000,0.05648,...,18.98,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,277.00000,0.35140,152.00000,0.2397,0.07016,...,25.74,39.42,184.60,1821.0,165.00000,0.86810,0.9387,265.0000,0.4087,124.00000
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,9456.00,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [3]:
# Classe
y = pd.read_csv("/content/saidas_breast.csv")
y

     0
0    0
1    0
2    0
3    0
4    0
..  ..
564  0
565  0
566  0
567  0
568  1

[569 rows x 1 columns]

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size = 0.25, random_state = 1)

In [6]:
X_treinamento.shape, y_treinamento.shape

((426, 30), (426, 1))

In [7]:
X_teste.shape, y_teste.shape

((143, 30), (143, 1))

In [8]:
import tensorflow as tf
from tensorflow.keras.models import Sequential

In [9]:
rede_neural = Sequential([
    tf.keras.layers.InputLayer(shape = (30, )),
    tf.keras.layers.Dense(units = 16, activation = "relu", kernel_initializer = "random_uniform"),
    tf.keras.layers.Dense(units = 16, activation = "relu", kernel_initializer = "random_uniform"),
    tf.keras.layers.Dense(units = 1, activation = "sigmoid")
])

In [10]:
rede_neural.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 16)             │           496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 16)             │           272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 785 (3.07 KB)

 Trainable params: 785 (3.07 KB)

 Non-trainable params: 0 (0.00 B)

In [11]:
rede_neural.compile(optimizer = "adam", loss = "binary_crossentropy", metrics = ["binary_accuracy"])

In [ ]:
rede_neural.fit(X_treinamento, y_treinamento, batch_size = 10, epochs = 100)

In [13]:
previsoes = rede_neural.predict(X_teste)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step

In [14]:
previsoes = previsoes > 0.5

In [15]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [16]:
accuracy_score(y_teste, previsoes)

0.9020979020979021

In [17]:
confusion_matrix(y_teste, previsoes)

array([[45, 10],
       [ 4, 84]])

In [18]:
rede_neural.evaluate(X_teste, y_teste)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.9001 - loss: 0.2633

[0.2544076442718506, 0.9020978808403015]

# Validação cruzada

In [ ]:
!pip install scikeras

In [ ]:
!pip install scikit-learn==1.5.2

In [23]:
import scikeras
from scikeras.wrappers import KerasClassifier
from sklearn.model_selection import cross_val_score
from tensorflow.keras import backend as K
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

In [24]:
X = pd.read_csv("/content/entradas_breast.csv")
y = pd.read_csv("/content/saidas_breast.csv")

In [25]:
X = X.values
y = y.values.ravel()

In [26]:
def criar_rede():
    K.clear_session()
    model = Sequential()
    model.add(Dense(64, activation='relu', input_shape=(X.shape[1],)))
    model.add(Dense(32, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    optimizer = Adam(learning_rate=0.001)
    model.compile(optimizer=optimizer,
                  loss="binary_crossentropy",
                  metrics=["accuracy"])
    return model

In [27]:
rede_neural = KerasClassifier(model=criar_rede, epochs=100, batch_size=10)

In [ ]:
resultados = cross_val_score(estimator=rede_neural, X=X, y=y, cv=10, scoring="accuracy")

In [29]:
resultados

array([0.84210526, 0.85964912, 0.89473684, 0.94736842, 0.8245614 ,
       0.87719298, 0.87719298, 0.87719298, 0.80701754, 0.91071429])

In [30]:
resultados.mean()

np.float64(0.8717731829573936)

In [31]:
resultados.std()

np.float64(0.03911000516658108)

# Overfitting - Dropout

In [32]:
# Não recomendado pois pode excluir dados importantes
def criar_rede_dropout():
    K.clear_session()
    model = Sequential([
        tf.keras.layers.InputLayer(shape= (30, )),
        tf.keras.layers.Dense(units = 16, activation = "relu", kernel_initializer = "random_uniform"),
        tf.keras.layers.Dropout(rate = 0.2),
        tf.keras.layers.Dense(units = 16, activation = "relu", kernel_initializer = "random_uniform"),
        tf.keras.layers.Dropout(rate = 0.2),
        tf.keras.layers.Dense(units = 1, activation = "sigmoid"),
    ])
    optimizer = Adam(learning_rate=0.001, clipvalue = 0.5)
    model.compile(optimizer=optimizer,
                  loss="binary_crossentropy",
                  metrics=["accuracy"])
    return model

In [33]:
rede_neural = KerasClassifier(model=criar_rede_dropout, epochs=100, batch_size=10)

In [ ]:
resultados = cross_val_score(estimator=rede_neural, X=X, y=y, cv=10, scoring="accuracy")

In [35]:
resultados

array([0.9122807 , 0.78947368, 0.85964912, 0.9122807 , 0.89473684,
       0.9122807 , 0.87719298, 0.89473684, 0.85964912, 0.91071429])

In [36]:
resultados.mean()

np.float64(0.8822994987468672)

In [37]:
resultados.std()

np.float64(0.03671808839354637)

# Tuning dos parâmetros

In [38]:
from sklearn.model_selection import GridSearchCV

In [39]:
X = pd.read_csv("/content/entradas_breast.csv")
y = pd.read_csv("/content/saidas_breast.csv")

In [52]:
# Não recomendado pois pode excluir dados importantes
def criar_rede_dropout(optimizer, loss, kernel_initializer, activation, neurons):
    K.clear_session()
    model = Sequential([
        tf.keras.layers.InputLayer(shape= (30, )),
        tf.keras.layers.Dense(units = neurons, activation = activation, kernel_initializer = kernel_initializer),
        tf.keras.layers.Dropout(rate = 0.2),
        tf.keras.layers.Dense(units = neurons, activation = activation, kernel_initializer = kernel_initializer),
        tf.keras.layers.Dropout(rate = 0.2),
        tf.keras.layers.Dense(units = 1, activation = "sigmoid"),
    ])

    model.compile(optimizer= optimizer,
                  loss= loss,
                  metrics=["binary_accuracy"])
    return model

In [53]:
rede_neural = KerasClassifier(model = criar_rede_dropout)

Poucos parâmetros para não demorar muito

In [54]:
params = {
    "batch_size": [10, 30],
    "epochs": [50],
    "model__optimizer": ["adam"],
    "model__loss": ["binary_crossentropy"],
    "model__kernel_initializer": ["random_uniform", "normal"],
    "model__activation": ["relu"],
    "model__neurons": [16]
}

In [55]:
grid_search = GridSearchCV(estimator = rede_neural, param_grid = params, scoring = "accuracy", cv = 5)

In [ ]:
grid_search = grid_search.fit(X, y)

In [57]:
best_params = grid_search.best_params_

In [58]:
best_params

{'batch_size': 30,
 'epochs': 50,
 'model__activation': 'relu',
 'model__kernel_initializer': 'random_uniform',
 'model__loss': 'binary_crossentropy',
 'model__neurons': 16,
 'model__optimizer': 'adam'}

In [59]:
best_precision = grid_search.best_score_
print(best_precision)

0.8893339543549137

# Classificação de um registro

In [65]:
import numpy as np

In [86]:
model = Sequential([
    tf.keras.layers.InputLayer(shape= (30, )),
    tf.keras.layers.Dense(units = 16, activation = "relu", kernel_initializer = "random_uniform"),
    tf.keras.layers.Dropout(rate = 0.2),
    tf.keras.layers.Dense(units = 16, activation = "relu", kernel_initializer = "random_uniform"),
    tf.keras.layers.Dropout(rate = 0.2),
    tf.keras.layers.Dense(units = 1, activation = "sigmoid"),
])

model.compile(optimizer = "adam", loss = "binary_crossentropy", metrics = ["binary_accuracy"])
model.fit(X, y, batch_size = 10, epochs = 50)

Epoch 1/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - binary_accuracy: 0.5185 - loss: 1.7137
Epoch 2/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6313 - loss: 0.5930
Epoch 3/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6427 - loss: 0.5832
Epoch 4/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.6974 - loss: 0.4945
Epoch 5/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7408 - loss: 0.4726
Epoch 6/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7625 - loss: 0.4735
Epoch 7/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7965 - loss: 0.4590
Epoch 8/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8128 - loss: 0.4249
Epoch 9/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.8214 - loss: 0.4204
Epoch 10/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8318 - loss: 0.4052
Epoch 11/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.8205 - loss: 0.4099
Epoch 12/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8286 - loss: 0.4022
Epoch 13/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.8550 - loss: 0.3650
Epoch 14/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8562 - loss: 0.3617
Epoch 15/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.8465 - loss: 0.3784
Epoch 16/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.8775 - loss: 0.3083
Epoch 17/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.8914 - loss: 0.2816
Epoch 18/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.8901 - loss: 0.2826
Epoch 19/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.8437 - loss: 0.3713
Epoch 20/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8844 - loss: 0.2946
Epoch 21/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.8978 - loss: 0.2602
Epoch 22/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8989 - loss: 0.2763
Epoch 23/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9099 - loss: 0.2730
Epoch 24/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.8960 - loss: 0.2917
Epoch 25/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.9035 - loss: 0.2717
Epoch 26/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.8872 - loss: 0.2701
Epoch 27/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.8844 - loss: 0.3024
Epoch 28/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - binary_accuracy: 0.8921 - loss: 0.2749
Epoch 29/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - binary_accuracy: 0.8709 - loss: 0.3062
Epoch 30/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - binary_accuracy: 0.8988 - loss: 0.2547
Epoch 31/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - binary_accuracy: 0.9196 - loss: 0.2380
Epoch 32/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.8871 - loss: 0.2781
Epoch 33/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.9062 - loss: 0.2320
Epoch 34/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8957 - loss: 0.2427
Epoch 35/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.9050 - loss: 0.2341
Epoch 36/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8977 - loss: 0.2584
Epoch 37/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9118 - loss: 0.2371
Epoch 38/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9228 - loss: 0.2064
Epoch 39/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9197 - loss: 0.2083
Epoch 40/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8890 - loss: 0.2832
Epoch 41/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8753 - loss: 0.2729
Epoch 42/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9062 - loss: 0.2340
Epoch 43/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8885 - loss: 0.2460
Epoch 44/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9002 - loss: 0.2494
Epoch 45/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.9082 - loss: 0.2106
Epoch 46/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.8818 - loss: 0.2605
Epoch 47/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9042 - loss: 0.2368
Epoch 48/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9010 - loss: 0.2252
Epoch 49/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8934 - loss: 0.2748
Epoch 50/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9364 - loss: 0.1995

In [71]:
new = np.array([[15.80, 8.34, 118, 900, 0.10, 0.26, 0.08, 0.134, 0.178, 0.20,
    0.05, 1098, 0.87, 4500, 145.2, 0.005, 0.04, 0.05, 0.015, 0.03,
    0.007, 23.15, 16.64, 178.5, 2018, 0.14, 0.185, 0.84, 158, 0.363]])

In [72]:
new

array([[1.580e+01, 8.340e+00, 1.180e+02, 9.000e+02, 1.000e-01, 2.600e-01,
        8.000e-02, 1.340e-01, 1.780e-01, 2.000e-01, 5.000e-02, 1.098e+03,
        8.700e-01, 4.500e+03, 1.452e+02, 5.000e-03, 4.000e-02, 5.000e-02,
        1.500e-02, 3.000e-02, 7.000e-03, 2.315e+01, 1.664e+01, 1.785e+02,
        2.018e+03, 1.400e-01, 1.850e-01, 8.400e-01, 1.580e+02, 3.630e-01]])

In [76]:
prev = model.predict(new)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step

In [78]:
prev = prev > 0.5

In [80]:
if prev:
  print("Malígno")
else:
  print("Benígno")

Malígno

# Salvando modelo treinado

In [81]:
model.save("classificador_breast.keras")

# Carregando modelo treinado

In [82]:
classificador_new = tf.keras.models.load_model("/content/classificador_breast.keras")

In [84]:
classificador_new.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_9 (Dense)                 │ (None, 16)             │           496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_6 (Dropout)             │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 16)             │           272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_7 (Dropout)             │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,357 (9.21 KB)

 Trainable params: 785 (3.07 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 1,572 (6.14 KB)

In [85]:
classificador_new.predict(new)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step

array([[1.]], dtype=float32)