<a href="https://colab.research.google.com/github/Matheusbcy/-Data-Science-IA-/blob/main/Deep%20Learning/Redes%20Neurais%20Artificiais/Regress%C3%A3o/Regress%C3%A3os_mais_valores_Games.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install tensorflow==2.16.1

In [1]:
import pandas as pd
import tensorflow as tf
import sklearn

In [4]:
from tensorflow.keras.layers import Dense, Dropout, Activation, Input
from tensorflow.keras.models import Model
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [5]:
base = pd.read_csv("/content/games.csv")
base.head()

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
base = base.drop("Other_Sales", axis = 1)
base = base.drop("Global_Sales", axis = 1)
base = base.drop("Developer", axis = 1)

In [7]:
base.shape

(16719, 13)

# EDA

In [8]:
base.isnull().sum()

Name                  2
Platform              0
Year_of_Release     269
Genre                 2
Publisher            54
NA_Sales              0
EU_Sales              0
JP_Sales              0
Critic_Score       8582
Critic_Count       8582
User_Score         6704
User_Count         9129
Rating             6769
dtype: int64

In [10]:
# Dropei todos os valores nulos so por ser exercicio para aprendizagem
base = base.dropna(axis = 0)
base.shape

(6825, 13)

In [11]:
base.isnull().sum()

Name               0
Platform           0
Year_of_Release    0
Genre              0
Publisher          0
NA_Sales           0
EU_Sales           0
JP_Sales           0
Critic_Score       0
Critic_Count       0
User_Score         0
User_Count         0
Rating             0
dtype: int64

In [12]:
base["Name"].value_counts()

Name
Need for Speed: Most Wanted                  8
Madden NFL 07                                8
LEGO Star Wars II: The Original Trilogy      8
The Sims 2                                   7
Terraria                                     7
                                            ..
Castlevania: Portrait of Ruin                1
Suzuki TT Superbikes                         1
Rumble Roses                                 1
Sherlock Holmes: The Mystery of the Mummy    1
STORM: Frontline Nation                      1
Name: count, Length: 4377, dtype: int64

In [13]:
base = base.drop("Name", axis = 1)

In [14]:
base.shape

(6825, 12)

In [15]:
base.columns

Index(['Platform', 'Year_of_Release', 'Genre', 'Publisher', 'NA_Sales',
       'EU_Sales', 'JP_Sales', 'Critic_Score', 'Critic_Count', 'User_Score',
       'User_Count', 'Rating'],
      dtype='object')

In [16]:
X = base.iloc[:, [0, 1, 2, 3, 7, 8, 9, 10, 11]].values

In [18]:
y_na = base.iloc[:, 4]
y_eu = base.iloc[:, 5]
y_jp = base.iloc[:, 6]

In [20]:
base["Platform"].value_counts()

Platform
PS2     1140
X360     858
PS3      769
PC       651
XB       565
Wii      479
DS       464
PSP      390
GC       348
PS4      239
GBA      237
XOne     159
3DS      155
PS       150
PSV      118
WiiU      89
DC        14
Name: count, dtype: int64

In [24]:
onehotencoder = ColumnTransformer(
    transformers = [
        ("OneHot", OneHotEncoder(), [0, 2, 3, 8])
    ],
    remainder = "passthrough"
)
X = onehotencoder.fit_transform(X).toarray()

In [26]:
X.shape

(6825, 303)

In [27]:
camada_entrada = Input(shape = (303, ))
camada_oculta1 = Dense(units = 153, activation = "relu")(camada_entrada)
camada_oculta2 = Dense(units = 153, activation = "relu")(camada_oculta1)
camada_saida1 = Dense(units = 1, activation = "linear")(camada_oculta2)
camada_saida2 = Dense(units = 1, activation = "linear")(camada_oculta2)
camada_saida3 = Dense(units = 1, activation = "linear")(camada_oculta2)

In [28]:
regressor = Model(inputs = camada_entrada, outputs = [camada_saida1, camada_saida2, camada_saida3])

In [29]:
regressor.compile(optimizer = "adam", loss = "mse")

In [30]:
regressor.fit(X, [y_na, y_eu, y_jp], epochs = 500, batch_size = 100)

Epoch 1/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - dense_2_loss: 2987.9326 - dense_3_loss: 656.8297 - dense_4_loss: 1094.6644 - loss: 4739.9033
Epoch 2/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 8.8732 - dense_3_loss: 21.6114 - dense_4_loss: 6.2034 - loss: 36.6928
Epoch 3/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 1.8601 - dense_3_loss: 1.8185 - dense_4_loss: 1.3023 - loss: 4.9813
Epoch 4/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 1.4974 - dense_3_loss: 1.1345 - dense_4_loss: 0.9327 - loss: 3.5640
Epoch 5/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - dense_2_loss: 2.4097 - dense_3_loss: 3.9703 - dense_4_loss: 0.9267 - loss: 7.3084
Epoch 6/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 1.8873 - dense_3_loss: 2.2260 - dense_4_loss: 0.5852 - loss: 4.7023
Epoch 7/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - dense_2_loss: 16.7687 - dense_3_loss: 45.0546 - dense_4_loss: 3.3015 - loss: 65.1413
Epoch 8/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - dense_2_loss: 5.8904 - dense_3_loss: 13.0445 - dense_4_loss: 1.5771 - loss: 20.5171
Epoch 9/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 8.7526 - dense_3_loss: 21.0900 - dense_4_loss: 1.4660 - loss: 31.3109
Epoch 10/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 28.2907 - dense_3_loss: 10.8266 - dense_4_loss: 4.6334 - loss: 43.7598
Epoch 11/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 0.8842 - dense_3_loss: 0.8795 - dense_4_loss: 0.2647 - loss: 2.0281
Epoch 12/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 0.9651 - dense_3_loss: 0.6598 - dense_4_loss: 0.2270 - loss: 1.8522
Epoch 13/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.8020 - dense_3_loss: 1.0608 - dense_4_loss: 0.3385 - loss: 2.2017
Epoch 14/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 2.7245 - dense_3_loss: 2.8309 - dense_4_loss: 0.3169 - loss: 5.8765
Epoch 15/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 11.8218 - dense_3_loss: 31.0139 - dense_4_loss: 1.6444 - loss: 44.4888
Epoch 16/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - dense_2_loss: 1.9443 - dense_3_loss: 6.8319 - dense_4_loss: 0.7661 - loss: 9.5357
Epoch 17/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 82.0289 - dense_3_loss: 156.8975 - dense_4_loss: 8.3412 - loss: 247.3339
Epoch 18/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 10.1188 - dense_3_loss: 40.9480 - dense_4_loss: 1.4856 - loss: 52.5625
Epoch 19/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 0.8603 - dense_3_loss: 0.7476 - dense_4_loss: 0.2437 - loss: 1.8520
Epoch 20/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 1.2497 - dense_3_loss: 0.7963 - dense_4_loss: 0.1611 - loss: 2.2075
Epoch 21/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.7966 - dense_3_loss: 0.4469 - dense_4_loss: 0.1452 - loss: 1.3889
Epoch 22/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 1.1394 - dense_3_loss: 0.7078 - dense_4_loss: 0.5092 - loss: 2.3567
Epoch 23/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.7491 - dense_3_loss: 0.5186 - dense_4_loss: 0.1202 - loss: 1.3881
Epoch 24/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.7085 - dense_3_loss: 0.5007 - dense_4_loss: 0.1233 - loss: 1.3319
Epoch 25/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 1.0788 - dense_3_loss: 0.4330 - dense_4_loss: 0.1766 - loss: 1.6887
Epoch 26/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 6.5012 - dense_3_loss: 0.7156 - dense_4_loss: 3.5319 - loss: 10.7527
Epoch 27/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 14.5425 - dense_3_loss: 1.9908 - dense_4_loss: 11.5347 - loss: 28.0709
Epoch 28/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 2.8099 - dense_3_loss: 1.0365 - dense_4_loss: 0.6375 - loss: 4.4846
Epoch 29/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 1.3926 - dense_3_loss: 1.1060 - dense_4_loss: 0.2540 - loss: 2.7532
Epoch 30/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.7109 - dense_3_loss: 0.5139 - dense_4_loss: 0.1334 - loss: 1.3571
Epoch 31/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 1.5629 - dense_3_loss: 1.0138 - dense_4_loss: 0.2520 - loss: 2.8287
Epoch 32/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - dense_2_loss: 0.7453 - dense_3_loss: 0.4709 - dense_4_loss: 0.1224 - loss: 1.3389
Epoch 33/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 1.0526 - dense_3_loss: 1.7227 - dense_4_loss: 0.2612 - loss: 3.0371
Epoch 34/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.8409 - dense_3_loss: 0.6797 - dense_4_loss: 0.1361 - loss: 1.6569
Epoch 35/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.2793 - dense_3_loss: 0.7345 - dense_4_loss: 0.2016 - loss: 2.2158
Epoch 36/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - dense_2_loss: 1.2139 - dense_3_loss: 1.0479 - dense_4_loss: 0.2175 - loss: 2.4797
Epoch 37/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - dense_2_loss: 1.0300 - dense_3_loss: 0.7167 - dense_4_loss: 0.2424 - loss: 1.9892
Epoch 38/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 1.1040 - dense_3_loss: 0.8477 - dense_4_loss: 0.4755 - loss: 2.4278
Epoch 39/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 0.9889 - dense_3_loss: 0.9395 - dense_4_loss: 0.2248 - loss: 2.1538
Epoch 40/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 1.5395 - dense_3_loss: 1.5584 - dense_4_loss: 0.1947 - loss: 3.2930
Epoch 41/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.9061 - dense_3_loss: 1.0861 - dense_4_loss: 2.4732 - loss: 5.4665
Epoch 42/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 5.6751 - dense_3_loss: 2.5764 - dense_4_loss: 3.8830 - loss: 12.1262
Epoch 43/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - dense_2_loss: 40.0696 - dense_3_loss: 8.0004 - dense_4_loss: 21.2722 - loss: 69.3465
Epoch 44/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 37.2187 - dense_3_loss: 7.9996 - dense_4_loss: 9.6883 - loss: 54.9161
Epoch 45/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 3.3692 - dense_3_loss: 1.4036 - dense_4_loss: 6.3218 - loss: 11.0964
Epoch 46/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 0.5888 - dense_3_loss: 0.3832 - dense_4_loss: 0.2199 - loss: 1.1918
Epoch 47/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 1.1542 - dense_3_loss: 0.9571 - dense_4_loss: 0.5184 - loss: 2.6294
Epoch 48/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 1.4010 - dense_3_loss: 1.3460 - dense_4_loss: 0.3766 - loss: 3.1233
Epoch 49/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 0.6859 - dense_3_loss: 1.0393 - dense_4_loss: 0.2548 - loss: 1.9801
Epoch 50/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.7337 - dense_3_loss: 0.6987 - dense_4_loss: 0.3371 - loss: 1.7689
Epoch 51/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 1.0581 - dense_3_loss: 1.4335 - dense_4_loss: 0.4218 - loss: 2.9137
Epoch 52/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.1148 - dense_3_loss: 0.9788 - dense_4_loss: 0.6218 - loss: 2.7150
Epoch 53/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.1104 - dense_3_loss: 1.1983 - dense_4_loss: 0.5036 - loss: 2.8126
Epoch 54/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 0.9457 - dense_3_loss: 1.0483 - dense_4_loss: 0.3427 - loss: 2.3374
Epoch 55/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 0.8208 - dense_3_loss: 1.1284 - dense_4_loss: 0.4443 - loss: 2.3942
Epoch 56/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.0016 - dense_3_loss: 1.0101 - dense_4_loss: 0.4192 - loss: 2.4319
Epoch 57/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 1.7223 - dense_3_loss: 4.2705 - dense_4_loss: 1.5226 - loss: 7.5165
Epoch 58/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.2871 - dense_3_loss: 2.4942 - dense_4_loss: 1.6469 - loss: 5.4301
Epoch 59/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.3717 - dense_3_loss: 1.4783 - dense_4_loss: 0.5641 - loss: 3.4145
Epoch 60/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.4374 - dense_3_loss: 1.4192 - dense_4_loss: 0.7590 - loss: 3.6167
Epoch 61/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 0.9575 - dense_3_loss: 0.7532 - dense_4_loss: 0.3543 - loss: 2.0655
Epoch 62/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.2269 - dense_3_loss: 2.2243 - dense_4_loss: 0.8780 - loss: 4.3288
Epoch 63/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 1.3966 - dense_3_loss: 2.6709 - dense_4_loss: 0.9144 - loss: 4.9795
Epoch 64/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 2.2898 - dense_3_loss: 2.6880 - dense_4_loss: 0.8450 - loss: 5.8238
Epoch 65/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.7144 - dense_3_loss: 1.2057 - dense_4_loss: 0.8069 - loss: 3.7269
Epoch 66/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - dense_2_loss: 2.2526 - dense_3_loss: 1.2625 - dense_4_loss: 0.6436 - loss: 4.1596
Epoch 67/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 7.6861 - dense_3_loss: 2.5309 - dense_4_loss: 1.6432 - loss: 11.8620
Epoch 68/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - dense_2_loss: 2.3716 - dense_3_loss: 1.4076 - dense_4_loss: 1.0524 - loss: 4.8315
Epoch 69/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 0.8625 - dense_3_loss: 0.7756 - dense_4_loss: 0.3146 - loss: 1.9524
Epoch 70/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 1.5001 - dense_3_loss: 3.2843 - dense_4_loss: 1.5475 - loss: 6.3326
Epoch 71/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - dense_2_loss: 2.8943 - dense_3_loss: 2.0344 - dense_4_loss: 0.8314 - loss: 5.7604
Epoch 72/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 2.2163 - dense_3_loss: 0.8327 - dense_4_loss: 0.5880 - loss: 3.6372
Epoch 73/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.6994 - dense_3_loss: 0.6092 - dense_4_loss: 0.3621 - loss: 2.6713
Epoch 74/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 1.7944 - dense_3_loss: 1.4197 - dense_4_loss: 0.6140 - loss: 3.8274
Epoch 75/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 1.0127 - dense_3_loss: 1.9791 - dense_4_loss: 1.4702 - loss: 4.4624
Epoch 76/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 4.1918 - dense_3_loss: 1.8968 - dense_4_loss: 0.9300 - loss: 7.0202
Epoch 77/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 3.6268 - dense_3_loss: 1.4220 - dense_4_loss: 1.1537 - loss: 6.1984
Epoch 78/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 10.5723 - dense_3_loss: 6.2117 - dense_4_loss: 4.5990 - loss: 21.3863
Epoch 79/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 4.1801 - dense_3_loss: 12.3526 - dense_4_loss: 9.4824 - loss: 26.0177
Epoch 80/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 10.8363 - dense_3_loss: 8.6681 - dense_4_loss: 2.9521 - loss: 22.4591
Epoch 81/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.8776 - dense_3_loss: 1.0787 - dense_4_loss: 0.1411 - loss: 3.0980
Epoch 82/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.7550 - dense_3_loss: 0.6498 - dense_4_loss: 0.1290 - loss: 1.5344
Epoch 83/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 2.1264 - dense_3_loss: 1.1396 - dense_4_loss: 0.1332 - loss: 3.3991
Epoch 84/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.8248 - dense_3_loss: 0.5738 - dense_4_loss: 0.2141 - loss: 1.6118
Epoch 85/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.0556 - dense_3_loss: 0.3417 - dense_4_loss: 0.1828 - loss: 1.5801
Epoch 86/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.9559 - dense_3_loss: 0.5632 - dense_4_loss: 0.1144 - loss: 1.6052
Epoch 87/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 6.6504 - dense_3_loss: 3.2942 - dense_4_loss: 0.3460 - loss: 10.2919
Epoch 88/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.8918 - dense_3_loss: 0.7970 - dense_4_loss: 0.1949 - loss: 1.8839
Epoch 89/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 0.9784 - dense_3_loss: 0.5465 - dense_4_loss: 0.1287 - loss: 1.6535
Epoch 90/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 1.1285 - dense_3_loss: 1.0909 - dense_4_loss: 0.2464 - loss: 2.4664
Epoch 91/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.0834 - dense_3_loss: 0.7454 - dense_4_loss: 0.1652 - loss: 1.9940
Epoch 92/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.8374 - dense_3_loss: 1.8444 - dense_4_loss: 0.8132 - loss: 4.4951
Epoch 93/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 2.0415 - dense_3_loss: 1.4549 - dense_4_loss: 0.7453 - loss: 4.2416
Epoch 94/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.3800 - dense_3_loss: 1.0618 - dense_4_loss: 0.3262 - loss: 2.7680
Epoch 95/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.1302 - dense_3_loss: 0.7896 - dense_4_loss: 0.4159 - loss: 2.3359
Epoch 96/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.3681 - dense_3_loss: 0.8557 - dense_4_loss: 0.3155 - loss: 2.5395
Epoch 97/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.8042 - dense_3_loss: 0.6543 - dense_4_loss: 0.3296 - loss: 1.7869
Epoch 98/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 2.2220 - dense_3_loss: 14.0366 - dense_4_loss: 4.5850 - loss: 20.8481
Epoch 99/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.7995 - dense_3_loss: 0.4239 - dense_4_loss: 0.2040 - loss: 1.4279
Epoch 100/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 2.4613 - dense_3_loss: 0.9645 - dense_4_loss: 0.2222 - loss: 3.6487
Epoch 101/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - dense_2_loss: 0.8481 - dense_3_loss: 0.4007 - dense_4_loss: 0.2122 - loss: 1.4609
Epoch 102/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 0.8550 - dense_3_loss: 0.4851 - dense_4_loss: 0.2135 - loss: 1.5537
Epoch 103/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - dense_2_loss: 0.7969 - dense_3_loss: 0.4395 - dense_4_loss: 0.2646 - loss: 1.5013
Epoch 104/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 4.3153 - dense_3_loss: 0.8955 - dense_4_loss: 2.1800 - loss: 7.3890
Epoch 105/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 1.8177 - dense_3_loss: 1.1496 - dense_4_loss: 2.0538 - loss: 5.0213
Epoch 106/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - dense_2_loss: 1.2798 - dense_3_loss: 1.2337 - dense_4_loss: 0.6100 - loss: 3.1235
Epoch 107/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 0.8585 - dense_3_loss: 0.5363 - dense_4_loss: 0.1058 - loss: 1.5009
Epoch 108/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.0339 - dense_3_loss: 0.5342 - dense_4_loss: 0.1858 - loss: 1.7537
Epoch 109/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.0473 - dense_3_loss: 0.5074 - dense_4_loss: 0.9901 - loss: 2.5454
Epoch 110/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.3991 - dense_3_loss: 0.6825 - dense_4_loss: 0.1166 - loss: 2.1983
Epoch 111/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.5345 - dense_3_loss: 0.7442 - dense_4_loss: 0.1933 - loss: 2.4720
Epoch 112/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.1318 - dense_3_loss: 0.7828 - dense_4_loss: 0.2839 - loss: 2.1973
Epoch 113/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 2.1991 - dense_3_loss: 0.8597 - dense_4_loss: 0.1955 - loss: 3.2549
Epoch 114/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.6091 - dense_3_loss: 0.3257 - dense_4_loss: 0.1523 - loss: 1.0865
Epoch 115/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 1.5193 - dense_3_loss: 0.9133 - dense_4_loss: 0.1899 - loss: 2.6232
Epoch 116/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 0.6843 - dense_3_loss: 0.5323 - dense_4_loss: 0.2476 - loss: 1.4648
Epoch 117/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.7326 - dense_3_loss: 0.6627 - dense_4_loss: 0.4983 - loss: 2.8936
Epoch 118/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.6708 - dense_3_loss: 0.5087 - dense_4_loss: 0.2309 - loss: 1.4107
Epoch 119/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 0.9846 - dense_3_loss: 0.4765 - dense_4_loss: 0.1953 - loss: 1.6565
Epoch 120/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.7275 - dense_3_loss: 0.4436 - dense_4_loss: 0.2391 - loss: 1.4104
Epoch 121/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.7050 - dense_3_loss: 1.0096 - dense_4_loss: 0.3336 - loss: 3.0485
Epoch 122/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 1.1858 - dense_3_loss: 0.7682 - dense_4_loss: 0.5227 - loss: 2.4769
Epoch 123/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.3150 - dense_3_loss: 0.5887 - dense_4_loss: 0.2133 - loss: 2.1175
Epoch 124/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 1.1775 - dense_3_loss: 0.4750 - dense_4_loss: 0.8500 - loss: 2.5029
Epoch 125/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 0.8564 - dense_3_loss: 1.3749 - dense_4_loss: 0.6093 - loss: 2.8413
Epoch 126/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.1224 - dense_3_loss: 0.7516 - dense_4_loss: 0.3191 - loss: 2.1933
Epoch 127/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 1.0155 - dense_3_loss: 0.5634 - dense_4_loss: 0.2469 - loss: 1.8257
Epoch 128/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 3.8384 - dense_3_loss: 1.4686 - dense_4_loss: 0.6885 - loss: 5.9969
Epoch 129/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.1977 - dense_3_loss: 0.4921 - dense_4_loss: 0.3566 - loss: 2.0461
Epoch 130/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 1.2136 - dense_3_loss: 0.5330 - dense_4_loss: 0.3470 - loss: 2.0937
Epoch 131/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.1218 - dense_3_loss: 0.5921 - dense_4_loss: 1.1033 - loss: 2.8172
Epoch 132/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.8347 - dense_3_loss: 0.4454 - dense_4_loss: 0.1352 - loss: 1.4151
Epoch 133/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 1.0362 - dense_3_loss: 0.6047 - dense_4_loss: 0.7818 - loss: 2.4230
Epoch 134/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - dense_2_loss: 0.7367 - dense_3_loss: 0.5084 - dense_4_loss: 0.2869 - loss: 1.5323
Epoch 135/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 1.0267 - dense_3_loss: 0.5425 - dense_4_loss: 0.2509 - loss: 1.8201
Epoch 136/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 1.5684 - dense_3_loss: 0.4917 - dense_4_loss: 0.5110 - loss: 2.5716
Epoch 137/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 1.1678 - dense_3_loss: 0.6407 - dense_4_loss: 0.1690 - loss: 1.9780
Epoch 138/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 0.6210 - dense_3_loss: 0.5785 - dense_4_loss: 0.2853 - loss: 1.4848
Epoch 139/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 1.3993 - dense_3_loss: 0.8109 - dense_4_loss: 0.3218 - loss: 2.5325
Epoch 140/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.9655 - dense_3_loss: 0.6300 - dense_4_loss: 0.2171 - loss: 1.8126
Epoch 141/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 0.9603 - dense_3_loss: 0.9180 - dense_4_loss: 0.5591 - loss: 2.4367
Epoch 142/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.6130 - dense_3_loss: 3.5837 - dense_4_loss: 3.7533 - loss: 8.9515
Epoch 143/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.0348 - dense_3_loss: 0.6515 - dense_4_loss: 0.1765 - loss: 1.8631
Epoch 144/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.0040 - dense_3_loss: 0.5064 - dense_4_loss: 0.0884 - loss: 1.5991
Epoch 145/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 0.8028 - dense_3_loss: 0.4128 - dense_4_loss: 0.1205 - loss: 1.3363
Epoch 146/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.7227 - dense_3_loss: 0.3936 - dense_4_loss: 0.0992 - loss: 1.2157
Epoch 147/500

In [32]:
previsao_na, previsao_eu, previsao_jp = regressor.predict(X)

214/214 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

In [35]:
previsao_na, previsao_na.mean()

(array([[1.9576147 ],
        [2.3846622 ],
        [2.024521  ],
        ...,
        [0.22185045],
        [0.1605838 ],
        [0.1155017 ]], dtype=float32),
 0.34330374)

In [36]:
y_na, y_na.mean()

(0        41.36
 2        15.68
 3        15.61
 6        11.28
 7        13.96
          ...
 16667     0.01
 16677     0.01
 16696     0.00
 16700     0.01
 16706     0.00
 Name: NA_Sales, Length: 6825, dtype: float64,
 0.3944835164835165)

In [37]:
from sklearn.metrics import mean_absolute_error

In [38]:
mean_absolute_error(y_na, previsao_na)

0.3167352984618791

In [39]:
mean_absolute_error(y_eu, previsao_eu)

0.21233160813963894

In [40]:
mean_absolute_error(y_jp, previsao_jp)

0.10229083425413558